name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1 description'
        required: false
        default: 'default_value'
      param2:
        description: 'Parameter 2 description'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flask pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/income-expense-calculator:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/income-expense-calculator:${{ github.sha }}

      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/income-expense-calculator:${{ github.sha }}
        run: |
          ssh user@your-server-ip <<EOF
            docker pull $DOCKER_IMAGE
            docker stop income-expense-calculator || true
            docker rm income-expense-calculator || true
            docker run -d -p 5000:5000 --name income-expense-calculator $DOCKER_IMAGE
          EOF
